"""Lyric composition from the topic graph (§13, §14, §15).

ADR-10 — **the words are composed, not generated by a language model.**

Context. §13 requires a LyricsDirector that owns subject selection with historical
awareness, and ACE-Step takes lyrics as *input*, so something has to produce text. §34
lists "lyrics model failure" as a condition the station must survive, implying a model may
exist.

Decision. The default lyric source is a **grammar over this station's own topic graph**,
not an LLM. :class:`LyricComposer` assembles sections from the accurate, pre-hedged
``teaching_points`` and ``phrases`` the topic library already carries.

Why, in order of weight:

1. **§14 becomes enforceable rather than hoped-for.** Every factual statement in a lyric
   is a string an author wrote and marked with a certainty level. An LLM asked to write
   about the dollar/gold relationship will produce "dollar up, gold down" as a flat fact,
   because that is what the training data says — and the §17 validator would then reject
   it, repeatedly, costing a generation cycle each time.
2. **§17's undetectable categories stop mattering.** Copyrighted lyrics and artist
   imitation cannot be detected from text (see :mod:`.validators`). Composing from our own
   corpus means there is no outside text to copy.
3. **Offline, free, instant, deterministic.** No API key, no cost per track, no network
   dependency in the §26 critical path, and a seeded composer is reproducible — which §64
   needs and §101 reporting benefits from.
4. **The fallback exists by construction.** §34's "lyrics model failure" path needs
   something to fall back *to*. Adding an LLM provider later behind the same interface
   makes this composer that fallback, rather than requiring a second one to be written.

Consequence, stated plainly: the lyrics are **more formulaic than a good LLM's**. The
grammar below is built to mitigate that — multiple phrase shapes per section role, pools
of connective lines per narrator perspective, and hooks assembled rather than templated —
but it is a real trade. Accepted because an unattended station that says accurate things
in a slightly repetitive way is better than one that says confident falsehoods about
markets, and §14 is explicit about which risk matters.

**Teaching points are inserted verbatim.** They are not rewritten to match the narrator's
perspective. Naive pronoun substitution produces the exact "generated" register §99 warns
about, and it can change meaning. Perspective instead controls the *connective* lines
around them, which is where a voice actually lives.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import dataclass

from tradefix_radio.contracts.lyrics import LyricLineV1, LyricsV1
from tradefix_radio.director.library import (
    ContentLibrary,
    PersonaDefinition,
    PerspectiveDefinition,
    TopicDefinition,
)
from tradefix_radio.director.selection import WeightedSelector
from tradefix_radio.lyrics.director import LyricPlan
from tradefix_radio.lyrics.validators import HEDGE_WORDS

#: Section roles, mapped from the many section names the formats use. Keeping the mapping
#: explicit means a format can invent a section name without the composer breaking.
_ROLE_BY_SECTION: dict[str, str] = {
    "intro": "open",
    "statement": "open",
    "call": "open",
    "verse": "body",
    "passage": "body",
    "lesson": "teach",
    "response": "answer",
    "hook": "hook",
    "phrase": "hook",
    "bridge": "turn",
    "outro": "close",
    "close": "close",
}

#: Brand phrasings (§16). Varied so repeated mentions across the station do not all read
#: identically, and all of them sound like something a station would actually say.
_BRAND_LINES: tuple[str, ...] = (
    "Trade Fix on the speakers while the tape moves",
    "this is Trade Fix, the market sets the tempo",
    "Trade Fix Radio, where the chart writes the chorus",
    "turn it up, Trade Fix is on",
    "Trade Fix in the background, discipline in the front",
    "you know the station: Trade Fix",
)

#: Connective lines by narrator perspective. These carry the voice; the teaching points
#: carry the content. Each pool is large enough that a thousand tracks do not exhaust it.
_CONNECTIVE: dict[str, tuple[str, ...]] = {
    "first_person": (
        "I wrote the rule before the candle got loud",
        "I read it again this morning",
        "my notes said the same thing last week",
        "I keep the plan where I can see it",
        "I am not in a hurry today",
        "I let the level come to me",
        "my size is already decided",
        "I checked the clock before the chart",
    ),
    "first_person_plural": (
        "we read the tape the same way every session",
        "we keep the same rule on a loud day",
        "we are early or we are flat",
        "we wrote it down so we cannot argue",
        "we size it before we like it",
        "we watch the same level everybody watches",
    ),
    "second_person": (
        "you decided this before the open",
        "you already know what the plan says",
        "you do not need this trade",
        "you can wait, the market is not leaving",
        "you set the size, the market sets the rest",
        "you are allowed to do nothing",
    ),
    "observer": (
        "the tape does not explain itself",
        "the level sits there and waits",
        "nobody rings a bell at the turn",
        "the range narrows and nobody speaks",
        "the book thins out and the moves get long",
        "the session changes hands without a sound",
    ),
    "narrator": (
        "the hours pass and the range holds",
        "somewhere a desk changes shift",
        "the number arrives and the room reacts",
        "the chart records it either way",
        "the day closes on whatever happened",
    ),
    "mentor": (
        "you will learn this the expensive way or the cheap way",
        "write it down now, you will want it later",
        "the mistake is not the loss, it is the reason",
        "nobody taught me this gently either",
        "keep the rule simple enough to follow when it is loud",
    ),
}

#: Short lines used to build hooks. Combined rather than used whole, so the hook of one
#: track is not the hook of another.
_HOOK_FRAGMENTS: tuple[str, ...] = (
    "same plan",
    "same size",
    "no rush",
    "let it come",
    "hold the line",
    "read it twice",
    "flat is fine",
    "wrote it down",
    "know the stop",
    "watch the level",
    "count the risk",
    "slow hands",
    "quiet hands",
    "eyes on the tape",
    "mind on the plan",
)

#: Hedging openers for §14. Used when the topic is contextual or speculative and the
#: teaching points alone might read as flat assertions.
_HEDGE_OPENERS: tuple[str, ...] = (
    "most days",
    "usually",
    "often enough to notice",
    "not always, but often",
    "some sessions",
    "more often than not",
)

#: Claim-free atmospheric lines, used as the **last** fallback when a long format has
#: exhausted both the perspective's connective pool and the topic's own phrases.
#:
#: Needed because without it the composer fell back to re-drawing a topic phrase, and a
#: 24-line storytelling format could emit the same line seven times — which the §17
#: repetition check correctly rejected as a looping generator. These make no market claims,
#: so they are safe with any topic at any certainty level.
_FILLER: tuple[str, ...] = (
    "the screen glows and the hours go by",
    "coffee goes cold while the range holds",
    "somebody somewhere is overtrading tonight",
    "the clock moves whether or not I do",
    "charts look obvious once they are history",
    "the quiet part is where the work happens",
    "nobody writes songs about the trades they skipped",
    "the spread widens and the room goes still",
    "another candle closes and nothing is settled",
    "I have read this level before",
    "the tape is patient even when I am not",
    "the desk lamp and the ticking and the waiting",
    "the market was here before me and will be after",
    "small decisions, repeated, are the whole thing",
    "the hard part was never the entry",
    "every chart is a record of other people's minds",
)

#: Lines that close a section without claiming anything.
_CLOSERS: tuple[str, ...] = (
    "that is the whole trick",
    "nothing clever about it",
    "that is all the edge is",
    "and then it is tomorrow",
    "and the tape keeps going",
    "that part never changes",
)


@dataclass
class ComposedLyric:
    """A composed lyric and how it was built."""

    lyrics: LyricsV1
    #: Section names in order, for the §46 detail page.
    sections: tuple[str, ...]
    #: Teaching points actually used, so §12's concept history is accurate.
    concepts: tuple[str, ...]
    rationale: tuple[str, ...]


class LyricComposer:
    """Builds lyric text from the topic graph. Deterministic for a seeded selector."""

    def __init__(self, library: ContentLibrary, selector: WeightedSelector) -> None:
        self._library = library
        self._selector = selector

    def compose(
        self,
        *,
        track_id: str,
        plan: LyricPlan,
        persona: PersonaDefinition | None = None,
    ) -> ComposedLyric | None:
        """Compose lyrics for a plan, or ``None`` for an instrumental track."""
        if not plan.enabled or plan.topic is None or plan.lyric_format is None:
            return None

        topic = plan.topic
        secondary = plan.secondary
        lyric_format = plan.lyric_format
        perspective = self._library.perspective(
            plan.spec.perspective or (persona.perspective if persona else "observer")
        )

        rationale: list[str] = [
            f"format {lyric_format.key}",
            f"perspective {perspective.key}",
            f"topic {topic.key} ({topic.certainty})",
        ]

        # The hook is composed once and reused wherever the format repeats it. That is
        # what makes it a hook rather than three different choruses.
        #
        # The format's own minimum is passed in because a hook-only format ("mostly
        # instrumental with vocal hook") has no other section to make up the word count,
        # and a 13-word output failed the format's declared 16-word floor.
        hook = self._compose_hook(
            topic,
            secondary,
            min_words=lyric_format.min_words if len(lyric_format.sections) == 1 else 0,
        )
        used_points: list[str] = []
        used_lines: set[str] = set()
        used_brand_lines: set[str] = set()
        sections: list[tuple[str, list[str]]] = []

        mentions_remaining = plan.spec.tradefix_mentions
        # Brand slots: prefer the hook for a brand-forward format (§16 says the station
        # anthem is where branding belongs), otherwise an ordinary line.
        brand_in_hook = bool(lyric_format.brand_forward) and mentions_remaining > 0

        for section in lyric_format.sections:
            role = _ROLE_BY_SECTION.get(section, "body")
            if role == "hook":
                lines = list(hook)
                if brand_in_hook and mentions_remaining > 0:
                    lines = self._inject_brand(lines, used_brand_lines)
                    mentions_remaining -= 1
                    brand_in_hook = False
            else:
                lines = self._compose_section(
                    role=role,
                    topic=topic,
                    secondary=secondary,
                    perspective=perspective,
                    persona=persona,
                    educational=plan.spec.educational_intensity,
                    used_lines=used_lines,
                    used_points=used_points,
                )
                if mentions_remaining > 0 and role in {"close", "body"}:
                    lines = self._inject_brand(lines, used_brand_lines)
                    mentions_remaining -= 1
            sections.append((section, lines))

        # Any brand mentions the sections could not place go in a trailing section, so the
        # count the blueprint promised is the count the lyric delivers.
        #
        # ALL of them, not one: a format whose sections are all hooks (minimal vocal) has
        # nowhere to inject during the loop above, and placing a single mention when two
        # were asked for left the lyric permanently disagreeing with its own blueprint.
        if mentions_remaining > 0:
            tail: list[str] = []
            for _ in range(mentions_remaining):
                # Distinct lines, so two mentions never read as a stutter. Shares
                # ``used_brand_lines`` with the in-loop path so a mention placed in a
                # section is not repeated here.
                tail.extend(self._inject_brand([], used_brand_lines))
            sections.append(("outro", tail))
            mentions_remaining = 0

        hedged = self._ensure_hedging(sections, topic, secondary)
        if hedged:
            rationale.append("hedging added for an uncertain topic (§14)")

        text = self._render_sections(sections)
        tagged_lines = tuple(
            LyricLineV1(section=section, text=line)
            for section, body in sections
            for line in body
        )

        return ComposedLyric(
            lyrics=LyricsV1(
                track_id=track_id,
                text=text,
                lines=tagged_lines,
                primary_topic=topic.key,
                secondary_topic=secondary.key if secondary else None,
                format=lyric_format.key,
                perspective=perspective.key,
                tradefix_mentions=plan.spec.tradefix_mentions,
                educational_intensity=plan.spec.educational_intensity,
                concepts_used=tuple(dict.fromkeys(used_points)),
            ),
            sections=tuple(section for section, _ in sections),
            concepts=tuple(dict.fromkeys(used_points)),
            rationale=tuple(rationale),
        )

    # -- sections ----------------------------------------------------------

    def _compose_hook(
        self,
        topic: TopicDefinition,
        secondary: TopicDefinition | None,
        *,
        min_words: int = 0,
    ) -> list[str]:
        """Two to four short lines, assembled from fragments and the topic's phrases.

        Assembled rather than drawn whole so two tracks on the same topic do not share a
        chorus — which is the repetition a listener notices fastest.

        ``min_words`` is honoured when the hook is the entire lyric: a second phrase is
        added until the format's own floor is reached, rather than emitting a lyric the
        format itself declares too short.
        """
        phrases = list(topic.phrases)
        if secondary:
            phrases.extend(secondary.phrases)
        anchor = self._selector.choose_from(phrases)
        fragments = self._selector.shuffled(_HOOK_FRAGMENTS)
        count = 2 if self._selector.rng.random() < 0.45 else 3
        lines = [anchor]
        lines.extend(fragments[:count])
        # A repeated closing fragment is what makes a hook feel like one.
        lines.append(fragments[0])

        remaining = [phrase for phrase in phrases if phrase != anchor]
        # Bounded: a hook that grew without limit would stop being a hook.
        while min_words and _word_count(lines) < min_words and remaining and len(lines) < 7:
            extra = self._selector.choose_from(remaining)
            remaining.remove(extra)
            # Inserted before the closing fragment so the hook still ends on its refrain.
            lines.insert(len(lines) - 1, extra)
        return lines

    def _compose_section(
        self,
        *,
        role: str,
        topic: TopicDefinition,
        secondary: TopicDefinition | None,
        perspective: PerspectiveDefinition,
        persona: PersonaDefinition | None,
        educational: float,
        used_lines: set[str],
        used_points: list[str],
    ) -> list[str]:
        """Build one non-hook section."""
        connective = _CONNECTIVE.get(perspective.key, _CONNECTIVE["observer"])
        lines: list[str] = []

        # How many lines the role wants. Teaching roles run longer because they carry
        # content; openers and closers are short by nature.
        target = {
            "open": 2,
            "body": 4,
            "teach": 4,
            "answer": 2,
            "turn": 2,
            "close": 2,
        }.get(role, 3)

        # Educational intensity decides the mix of teaching points to atmosphere. A
        # 0.9-intensity "educational bars" section is nearly all content; a 0.15 "minimal
        # vocal" is nearly all mood.
        teach_slots = max(0, round(target * educational))
        if role == "teach":
            teach_slots = max(teach_slots, target - 1)
        if role in {"open", "close"}:
            teach_slots = min(teach_slots, 1)

        points = [
            point
            for point in (*topic.teaching_points, *(secondary.teaching_points if secondary else ()))
            if point not in used_points
        ]
        for _ in range(teach_slots):
            if not points:
                break
            point = self._selector.choose_from(points)
            points.remove(point)
            used_points.append(point)
            lines.append(point)

        # Fallback ladder, most on-theme first. The final rung matters: without it a long
        # format exhausted every pool and re-drew the same topic phrase, which §17's
        # repetition check then rejected as a looping generator.
        while len(lines) < target:
            pool = [line for line in connective if line not in used_lines]
            if not pool:
                pool = [phrase for phrase in topic.phrases if phrase not in used_lines]
            if not pool and secondary is not None:
                pool = [
                    phrase for phrase in secondary.phrases if phrase not in used_lines
                ]
            if not pool:
                pool = [line for line in _FILLER if line not in used_lines]
            if not pool:
                # Every pool exhausted in one track, which needs a format far longer than
                # any §15 format declares. Stop rather than repeat: a slightly short
                # section is better than a line the validator will reject.
                break
            line = self._selector.choose_from(pool)
            used_lines.add(line)
            lines.append(line)

        # §100: a persona's signature habits are what make it feel like a different
        # artist rather than a different label. Dropped in occasionally rather than every
        # section, so it reads as a habit and not a catchphrase.
        if (
            persona is not None
            and persona.signature
            and role in {"body", "teach"}
            and self._selector.rng.random() < 0.25
        ):
            signature = self._selector.choose_from(persona.signature)
            if signature not in used_lines:
                used_lines.add(signature)
                lines.append(signature)

        if role == "close" and self._selector.rng.random() < 0.6:
            lines.append(self._selector.choose_from(_CLOSERS))

        return self._selector.shuffled(lines) if role == "body" else lines

    def _inject_brand(self, lines: list[str], used: set[str]) -> list[str]:
        """Place one brand mention without displacing content or repeating itself.

        Appended rather than substituted: replacing a line could remove a teaching point
        and silently lower the educational payload the blueprint promised.

        ``used`` carries the brand lines already placed anywhere in this lyric. The
        trailing-tail path always tracked this; this path did not, so a two-mention lyric
        could print the same brand line in two sections — a stutter, and exactly the thing
        the tail path's own comment says to avoid.
        """
        available = [line for line in _BRAND_LINES if line not in used] or list(
            _BRAND_LINES
        )
        line = self._selector.choose_from(available)
        used.add(line)
        return [*lines, line]

    def _ensure_hedging(
        self,
        sections: list[tuple[str, list[str]]],
        topic: TopicDefinition,
        secondary: TopicDefinition | None,
    ) -> bool:
        """Guarantee §14 hedging is present when the topic requires it.

        Belt and braces. The topic graph's teaching points for contextual and speculative
        topics are already written with qualifiers, but a section mix that happened to use
        none of them would fail validation and cost a regeneration. Adding an opener is
        cheaper and cannot make the text wrong.
        """
        needs_hedge = topic.requires_hedging or (
            secondary is not None and secondary.requires_hedging
        )
        if not needs_hedge:
            return False

        rendered = " ".join(
            line for _, body in sections for line in body
        ).lower()
        if set(re.findall(r"[a-z']+", rendered)) & HEDGE_WORDS:
            return False

        opener = self._selector.choose_from(_HEDGE_OPENERS)
        for index, (section, body) in enumerate(sections):
            if body:
                sections[index] = (section, [f"{opener}, {body[0]}", *body[1:]])
                return True
        return False

    @staticmethod
    def _render_sections(sections: Sequence[tuple[str, list[str]]]) -> str:
        """Render with inline section tags, which is what ACE-Step expects."""
        blocks: list[str] = []
        for section, lines in sections:
            if not lines:
                continue
            blocks.append(f"[{section}]")
            blocks.extend(lines)
            blocks.append("")
        return "\n".join(blocks).strip()


def _word_count(lines: Sequence[str]) -> int:
    """Words across a set of lines, counted the way the validator counts them."""
    return sum(len(re.findall(r"[a-z0-9']+", line.lower())) for line in lines)


__all__ = ["ComposedLyric", "LyricComposer"]
