"""provider_submissions

Records what the generation provider was actually sent (§7.9, §7.10, §7.26).

Additive only: one new table, no `batch_alter_table` against an existing one. That matters
because of what `docs/MIGRATIONS.md` documents — a batch rebuild of a parent table under
`ON DELETE CASCADE` drops its children with it — and the reason this migration is safe is
that it never rebuilds anything. No backfill either: nothing was recorded before this table
existed, and inventing submissions for historical tracks would put fabricated prompts in the
one place meant to be the record of what truly went to the model.

Revision ID: 185b03dd54d4
Revises: a8fa42dca4ec
Created: 2026-10-03 23:03:59.357595+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate renders our custom column types by their fully qualified name
# (`tradefix_radio.persistence.types.UtcDateTime()`), so the top-level package name
# must be bound in this module. A plain `import a.b.c` binds `a`, which is exactly
# what that rendering needs — an aliased import would not.
import tradefix_radio.persistence.types

revision: str = "185b03dd54d4"
down_revision: str | None = "a8fa42dca4ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_submissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model_identifier", sa.String(length=128), nullable=False),
        sa.Column("caption", sa.Text(), nullable=False),
        sa.Column("requested_lyrics", sa.Text(), nullable=True),
        sa.Column("provider_lyrics", sa.Text(), nullable=False),
        sa.Column("lyrics_modified", sa.Boolean(), nullable=False),
        sa.Column("lyric_notes", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("instrumental", sa.Boolean(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("inference_steps", sa.Integer(), nullable=False),
        sa.Column("guidance_scale", sa.Float(), nullable=False),
        sa.Column("profile", sa.String(length=32), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("bpm", sa.Integer(), nullable=False),
        sa.Column("key_scale", sa.String(length=48), nullable=False),
        sa.Column("warnings", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("created_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.track_id"],
            name=op.f("fk_provider_submissions_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_submissions")),
    )
    with op.batch_alter_table("provider_submissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_provider_submissions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_provider_submissions_instrumental"), ["instrumental"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_provider_submissions_lyrics_modified"), ["lyrics_modified"], unique=False
        )
        batch_op.create_index(
            "ix_provider_submissions_track_attempt", ["track_id", "attempt"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_provider_submissions_track_id"), ["track_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider_submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_submissions_track_id"))
        batch_op.drop_index("ix_provider_submissions_track_attempt")
        batch_op.drop_index(batch_op.f("ix_provider_submissions_lyrics_modified"))
        batch_op.drop_index(batch_op.f("ix_provider_submissions_instrumental"))
        batch_op.drop_index(batch_op.f("ix_provider_submissions_created_at"))

    op.drop_table("provider_submissions")
    # ### end Alembic commands ###
