"""Operator feedback: a human's opinion of a track, kept apart from technical QC.

A table of its own rather than columns on `tracks`, because the two kinds of judgement
must not be confusable. QC is measured and decides what may broadcast; this is an opinion
and decides nothing automatically. Nothing on the generation path reads this table.

Revision ID: cda89a476c06
Revises: 161f873f4932
Created: 2026-10-03 14:23:56.600687+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate renders our custom column types by their fully qualified name
# (`tradefix_radio.persistence.types.UtcDateTime()`), so the top-level package name
# must be bound in this module. A plain `import a.b.c` binds `a`, which is exactly
# what that rendering needs — an aliased import would not.
import tradefix_radio.persistence.types

revision: str = 'cda89a476c06'
down_revision: str | None = '161f873f4932'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
    sa.Column('track_id', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('market_regime', sa.String(length=48), nullable=True),
    sa.Column('elapsed_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_feedback'))
    )
    with op.batch_alter_table('operator_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_feedback_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_feedback_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_feedback_symbol'), ['symbol'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_operator_feedback_track_id'), ['track_id'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_operator_feedback_verdict'), ['verdict'], unique=False)
        batch_op.create_index('ix_operator_feedback_verdict_at', ['verdict', 'at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_operator_feedback_verdict_at')
        batch_op.drop_index(batch_op.f('ix_operator_feedback_verdict'))
        batch_op.drop_index(batch_op.f('ix_operator_feedback_track_id'))
        batch_op.drop_index(batch_op.f('ix_operator_feedback_symbol'))
        batch_op.drop_index(batch_op.f('ix_operator_feedback_reason'))
        batch_op.drop_index(batch_op.f('ix_operator_feedback_at'))

    op.drop_table('operator_feedback')
    # ### end Alembic commands ###
