"""phase 6 evidence columns

Revision ID: fde97de71f41
Revises: 01e661a92fb9
Created: 2026-10-03 02:03:05.638302+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate renders our custom column types by their fully qualified name
# (`tradefix_radio.persistence.types.UtcDateTime()`), so the top-level package name
# must be bound in this module. A plain `import a.b.c` binds `a`, which is exactly
# what that rendering needs — an aliased import would not.
import tradefix_radio.persistence.types  # noqa: F401 - referenced by rendered types

revision: str = "fde97de71f41"
down_revision: str | None = "01e661a92fb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audio_fingerprints", schema=None) as batch_op:
        batch_op.add_column(sa.Column("canonical_sha256", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("fingerprint_provider", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("fingerprint_version", sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column("fingerprint_value", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("embedding_version", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_audio_fingerprints_canonical_sha256"), ["canonical_sha256"], unique=False
        )

    # The two NOT NULL additions below carry a server default that autogenerate does not
    # emit. Without one, adding a non-nullable column to a table that already has rows fails
    # outright — and these tables do have rows the moment Phase 6 has processed a track. The
    # same defaults are declared on the models, so the schema and the mapping agree and
    # `alembic check` stays clean.
    with op.batch_alter_table("lyric_fingerprints", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tradefix_mentions", sa.Integer(), nullable=False, server_default=sa.text("0")
            )
        )

    with op.batch_alter_table("mastering_results", schema=None) as batch_op:
        batch_op.add_column(sa.Column("true_peak_ceiling_dbtp", sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "peak_constrained",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.create_index(
            batch_op.f("ix_mastering_results_peak_constrained"), ["peak_constrained"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mastering_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mastering_results_peak_constrained"))
        batch_op.drop_column("peak_constrained")
        batch_op.drop_column("true_peak_ceiling_dbtp")

    with op.batch_alter_table("lyric_fingerprints", schema=None) as batch_op:
        batch_op.drop_column("tradefix_mentions")

    with op.batch_alter_table("audio_fingerprints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audio_fingerprints_canonical_sha256"))
        batch_op.drop_column("embedding_version")
        batch_op.drop_column("fingerprint_value")
        batch_op.drop_column("fingerprint_version")
        batch_op.drop_column("fingerprint_provider")
        batch_op.drop_column("canonical_sha256")

    # ### end Alembic commands ###
