"""phase 6 qc originality mastering

Revision ID: 01e661a92fb9
Revises: 6213f53625cc
Created: 2026-10-03 01:33:15.792490+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate renders our custom column types by their fully qualified name
# (`tradefix_radio.persistence.types.UtcDateTime()`), so the top-level package name
# must be bound in this module. A plain `import a.b.c` binds `a`, which is exactly
# what that rendering needs — an aliased import would not.
import tradefix_radio.persistence.types

revision: str = "01e661a92fb9"
down_revision: str | None = "6213f53625cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_features",
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("channels", sa.Integer(), nullable=False),
        sa.Column("peak", sa.Float(), nullable=False),
        sa.Column("rms", sa.Float(), nullable=False),
        sa.Column("crest_factor", sa.Float(), nullable=False),
        sa.Column("dc_offset", sa.Float(), nullable=False),
        sa.Column("integrated_lufs", sa.Float(), nullable=True),
        sa.Column("spectral_centroid", sa.Float(), nullable=False),
        sa.Column("spectral_bandwidth", sa.Float(), nullable=False),
        sa.Column("spectral_rolloff", sa.Float(), nullable=False),
        sa.Column("zero_crossing_rate", sa.Float(), nullable=False),
        sa.Column("stereo_correlation", sa.Float(), nullable=False),
        sa.Column("silence_ratio", sa.Float(), nullable=False),
        sa.Column("clipped_sample_ratio", sa.Float(), nullable=False),
        sa.Column("tempo", sa.Float(), nullable=True),
        sa.Column("musical_key", sa.String(length=32), nullable=True),
        sa.Column("rms_profile", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("backend", sa.String(length=16), nullable=False),
        sa.Column("computed_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.track_id"],
            name=op.f("fk_audio_features_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("track_id", name=op.f("pk_audio_features")),
    )
    with op.batch_alter_table("audio_features", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audio_features_computed_at"), ["computed_at"], unique=False
        )

    op.create_table(
        "lyric_fingerprints",
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("line_hashes", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("shingles", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("hook_hashes", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("unique_word_ratio", sa.Float(), nullable=False),
        sa.Column("internal_repetition", sa.Float(), nullable=False),
        sa.Column("computed_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.track_id"],
            name=op.f("fk_lyric_fingerprints_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("track_id", name=op.f("pk_lyric_fingerprints")),
    )
    with op.batch_alter_table("lyric_fingerprints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lyric_fingerprints_computed_at"), ["computed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lyric_fingerprints_content_hash"), ["content_hash"], unique=False
        )

    op.create_table(
        "mastering_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("target_lufs", sa.Float(), nullable=False),
        sa.Column("measured_lufs_before", sa.Float(), nullable=True),
        sa.Column("measured_lufs_after", sa.Float(), nullable=True),
        sa.Column("true_peak_dbtp", sa.Float(), nullable=True),
        sa.Column("gain_applied_db", sa.Float(), nullable=True),
        sa.Column("trimmed_start_seconds", sa.Float(), nullable=False),
        sa.Column("trimmed_end_seconds", sa.Float(), nullable=False),
        sa.Column("duration_before", sa.Float(), nullable=False),
        sa.Column("duration_after", sa.Float(), nullable=False),
        sa.Column("elapsed_seconds", sa.Float(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("mastered_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.track_id"],
            name=op.f("fk_mastering_results_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mastering_results")),
    )
    with op.batch_alter_table("mastering_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mastering_results_mastered_at"), ["mastered_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_mastering_results_outcome"), ["outcome"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_mastering_results_track_id"), ["track_id"], unique=False
        )

    op.create_table(
        "track_qc_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("passed_count", sa.Integer(), nullable=False),
        sa.Column("warned_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("analysis_backend", sa.String(length=16), nullable=False),
        sa.Column("elapsed_seconds", sa.Float(), nullable=False),
        sa.Column("evaluated_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.track_id"],
            name=op.f("fk_track_qc_results_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_track_qc_results")),
    )
    with op.batch_alter_table("track_qc_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_track_qc_results_evaluated_at"), ["evaluated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_track_qc_results_stage"), ["stage"], unique=False)
        batch_op.create_index(batch_op.f("ix_track_qc_results_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_track_qc_results_track_id"), ["track_id"], unique=False
        )

    op.create_table(
        "track_qc_checks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("result_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=24), nullable=False),
        sa.Column("threshold", sa.String(length=96), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["track_qc_results.id"],
            name=op.f("fk_track_qc_checks_result_id_track_qc_results"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_track_qc_checks")),
    )
    with op.batch_alter_table("track_qc_checks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_track_qc_checks_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_track_qc_checks_result_id"), ["result_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_track_qc_checks_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track_qc_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_track_qc_checks_status"))
        batch_op.drop_index(batch_op.f("ix_track_qc_checks_result_id"))
        batch_op.drop_index(batch_op.f("ix_track_qc_checks_name"))

    op.drop_table("track_qc_checks")
    with op.batch_alter_table("track_qc_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_track_qc_results_track_id"))
        batch_op.drop_index(batch_op.f("ix_track_qc_results_status"))
        batch_op.drop_index(batch_op.f("ix_track_qc_results_stage"))
        batch_op.drop_index(batch_op.f("ix_track_qc_results_evaluated_at"))

    op.drop_table("track_qc_results")
    with op.batch_alter_table("mastering_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mastering_results_track_id"))
        batch_op.drop_index(batch_op.f("ix_mastering_results_outcome"))
        batch_op.drop_index(batch_op.f("ix_mastering_results_mastered_at"))

    op.drop_table("mastering_results")
    with op.batch_alter_table("lyric_fingerprints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lyric_fingerprints_content_hash"))
        batch_op.drop_index(batch_op.f("ix_lyric_fingerprints_computed_at"))

    op.drop_table("lyric_fingerprints")
    with op.batch_alter_table("audio_features", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audio_features_computed_at"))

    op.drop_table("audio_features")
    # ### end Alembic commands ###
