"""phase 6 composition energy

Revision ID: 7bcc4aaf4511
Revises: fde97de71f41
Created: 2026-10-03 03:30:46.716862+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate renders our custom column types by their fully qualified name
# (`tradefix_radio.persistence.types.UtcDateTime()`), so the top-level package name
# must be bound in this module. A plain `import a.b.c` binds `a`, which is exactly
# what that rendering needs — an aliased import would not.
import tradefix_radio.persistence.types  # noqa: F401 - referenced by rendered types

revision: str = "7bcc4aaf4511"
down_revision: str | None = "fde97de71f41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("composition_energy", sa.Float(), server_default=sa.text("0"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_column("composition_energy")

    # ### end Alembic commands ###
