"""initial schema

Revision ID: 6213f53625cc
Revises:
Created: 2026-10-02 07:49:13.005222+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate renders our custom column types by their fully qualified name
# (`tradefix_radio.persistence.types.UtcDateTime()`), so the top-level package name
# must be bound in this module. A plain `import a.b.c` binds `a`, which is exactly
# what that rendering needs — an aliased import would not.
import tradefix_radio.persistence.types

revision: str = "6213f53625cc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_jobs",
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Float(), nullable=False),
        sa.Column("lease_owner", sa.String(length=96), nullable=True),
        sa.Column(
            "lease_expires_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=True
        ),
        sa.Column("created_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("started_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=True),
        sa.Column("finished_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=True),
        sa.Column("generation_seconds", sa.Float(), nullable=True),
        sa.Column("peak_vram_bytes", sa.Integer(), nullable=True),
        sa.Column("error_kind", sa.String(length=48), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column(
            "request_payload", tradefix_radio.persistence.types.PortableJson(), nullable=True
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_generation_jobs")),
    )
    with op.batch_alter_table("generation_jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_generation_jobs_claim", ["state", "priority", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_generation_jobs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_generation_jobs_error_kind"), ["error_kind"], unique=False
        )
        batch_op.create_index(
            "ix_generation_jobs_lease", ["lease_owner", "lease_expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_generation_jobs_lease_expires_at"), ["lease_expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_generation_jobs_lease_owner"), ["lease_owner"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_generation_jobs_priority"), ["priority"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_jobs_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_jobs_state"), ["state"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_jobs_track_id"), ["track_id"], unique=False)

    op.create_table(
        "health_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("component", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("previous_status", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.String(length=500), nullable=False),
        sa.Column("measurements", tradefix_radio.persistence.types.PortableJson(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_events")),
    )
    with op.batch_alter_table("health_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_health_events_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_health_events_component"), ["component"], unique=False)
        batch_op.create_index(batch_op.f("ix_health_events_status"), ["status"], unique=False)

    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timestamp", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("bid", sa.Float(), nullable=False),
        sa.Column("ask", sa.Float(), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("tick_volume", sa.Float(), nullable=True),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_snapshots")),
    )
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_market_snapshots_symbol"), ["symbol"], unique=False)
        batch_op.create_index(
            "ix_market_snapshots_symbol_timestamp", ["symbol", "timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_market_snapshots_synthetic"), ["synthetic"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_market_snapshots_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "market_states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timestamp", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("regime", sa.String(length=48), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("session", sa.String(length=48), nullable=False),
        sa.Column("feed_status", sa.String(length=16), nullable=False),
        sa.Column("energy", sa.Float(), nullable=False),
        sa.Column("energy_velocity", sa.Float(), nullable=False),
        sa.Column("volatility", sa.Float(), nullable=False),
        sa.Column("trend_strength", sa.Float(), nullable=False),
        sa.Column("momentum", sa.Float(), nullable=False),
        sa.Column("compression", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("regime_age_seconds", sa.Float(), nullable=False),
        sa.Column("features", tradefix_radio.persistence.types.PortableJson(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_states")),
    )
    with op.batch_alter_table("market_states", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_market_states_feed_status"), ["feed_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_market_states_regime"), ["regime"], unique=False)
        batch_op.create_index(batch_op.f("ix_market_states_session"), ["session"], unique=False)
        batch_op.create_index(batch_op.f("ix_market_states_symbol"), ["symbol"], unique=False)
        batch_op.create_index(
            "ix_market_states_symbol_timestamp", ["symbol", "timestamp"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_market_states_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "metric_samples",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("name", sa.String(length=96), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("labels", tradefix_radio.persistence.types.PortableJson(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_samples")),
    )
    with op.batch_alter_table("metric_samples", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_metric_samples_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_metric_samples_name"), ["name"], unique=False)
        batch_op.create_index("ix_metric_samples_name_at", ["name", "at"], unique=False)

    op.create_table(
        "play_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("started_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("ended_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=True),
        sa.Column("played_seconds", sa.Float(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("tier", sa.String(length=24), nullable=False),
        sa.Column("transition_in", sa.String(length=32), nullable=False),
        sa.Column("end_reason", sa.String(length=48), nullable=True),
        sa.Column("regime_at_play", sa.String(length=48), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_play_events")),
    )
    with op.batch_alter_table("play_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_play_events_completed"), ["completed"], unique=False)
        batch_op.create_index(batch_op.f("ix_play_events_started_at"), ["started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_play_events_tier"), ["tier"], unique=False)
        batch_op.create_index(batch_op.f("ix_play_events_track_id"), ["track_id"], unique=False)

    op.create_table(
        "queue_items",
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("lock_level", sa.String(length=24), nullable=False),
        sa.Column("tier", sa.String(length=24), nullable=False),
        sa.Column("transition_in", sa.String(length=32), nullable=False),
        sa.Column("transition_seconds", sa.Float(), nullable=False),
        sa.Column("generation_progress", sa.Float(), nullable=False),
        sa.Column("enqueued_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("started_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=True),
        sa.Column("finished_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=True),
        sa.Column("display", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.PrimaryKeyConstraint("item_id", name=op.f("pk_queue_items")),
    )
    with op.batch_alter_table("queue_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_queue_items_enqueued_at"), ["enqueued_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_queue_items_lock_level"), ["lock_level"], unique=False)
        batch_op.create_index(batch_op.f("ix_queue_items_position"), ["position"], unique=False)
        batch_op.create_index(batch_op.f("ix_queue_items_state"), ["state"], unique=False)
        batch_op.create_index("ix_queue_items_state_position", ["state", "position"], unique=False)
        batch_op.create_index(batch_op.f("ix_queue_items_tier"), ["tier"], unique=False)
        batch_op.create_index(batch_op.f("ix_queue_items_track_id"), ["track_id"], unique=False)

    op.create_table(
        "radio_memory",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("updated_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_radio_memory")),
    )
    op.create_table(
        "setting_overrides",
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("value", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("updated_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_setting_overrides")),
    )
    op.create_table(
        "similarity_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("novelty_score", sa.Float(), nullable=False),
        sa.Column("max_similarity", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("closest_track_id", sa.String(length=64), nullable=True),
        sa.Column("deciding_component", sa.String(length=48), nullable=True),
        sa.Column("components", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("compared_against", sa.Integer(), nullable=False),
        sa.Column("evaluated_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_similarity_results")),
    )
    with op.batch_alter_table("similarity_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_similarity_results_evaluated_at"), ["evaluated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_similarity_results_track_id"), ["track_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_similarity_results_verdict"), ["verdict"], unique=False
        )

    op.create_table(
        "state_transitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("from_state", sa.String(length=32), nullable=True),
        sa.Column("to_state", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=96), nullable=False),
        sa.Column("detail", tradefix_radio.persistence.types.PortableJson(), nullable=True),
        sa.Column("at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_state_transitions")),
    )
    with op.batch_alter_table("state_transitions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_state_transitions_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_state_transitions_reason"), ["reason"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_state_transitions_to_state"), ["to_state"], unique=False
        )
        batch_op.create_index("ix_state_transitions_track_at", ["track_id", "at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_state_transitions_track_id"), ["track_id"], unique=False
        )

    op.create_table(
        "station_ids",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("text", sa.String(length=400), nullable=False),
        sa.Column("audio_path", sa.String(length=1024), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("context", sa.String(length=48), nullable=False),
        sa.Column("play_count", sa.Integer(), nullable=False),
        sa.Column("last_played_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_station_ids")),
    )
    with op.batch_alter_table("station_ids", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_station_ids_context"), ["context"], unique=False)
        batch_op.create_index(batch_op.f("ix_station_ids_enabled"), ["enabled"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_station_ids_last_played_at"), ["last_played_at"], unique=False
        )

    op.create_table(
        "system_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("service", sa.String(length=32), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("event", sa.String(length=96), nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=True),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("market_regime", sa.String(length=48), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("detail", tradefix_radio.persistence.types.PortableJson(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_events")),
    )
    with op.batch_alter_table("system_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_system_events_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_events_event"), ["event"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_events_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_events_level"), ["level"], unique=False)
        batch_op.create_index("ix_system_events_level_at", ["level", "at"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_events_service"), ["service"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_events_track_id"), ["track_id"], unique=False)

    op.create_table(
        "topics",
        sa.Column("key", sa.String(length=96), nullable=False),
        sa.Column("category", sa.String(length=48), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("certainty", sa.String(length=24), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("detail", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("last_used_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_topics")),
    )
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_topics_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_topics_certainty"), ["certainty"], unique=False)
        batch_op.create_index(batch_op.f("ix_topics_enabled"), ["enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_topics_last_used_at"), ["last_used_at"], unique=False)

    op.create_table(
        "track_titles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("normalised", sa.String(length=160), nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_track_titles")),
    )
    with op.batch_alter_table("track_titles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_track_titles_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_track_titles_normalised"), ["normalised"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_track_titles_title"), ["title"], unique=False)
        batch_op.create_index(batch_op.f("ix_track_titles_track_id"), ["track_id"], unique=False)

    op.create_table(
        "tracks",
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("persona_id", sa.String(length=48), nullable=True),
        sa.Column("genre", sa.String(length=64), nullable=False),
        sa.Column("secondary_genre", sa.String(length=64), nullable=True),
        sa.Column("bpm", sa.Integer(), nullable=False),
        sa.Column("musical_key", sa.String(length=32), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("is_instrumental", sa.Boolean(), nullable=False),
        sa.Column("vocal_style", sa.String(length=32), nullable=False),
        sa.Column("primary_topic", sa.String(length=96), nullable=True),
        sa.Column("secondary_topic", sa.String(length=96), nullable=True),
        sa.Column("regime_at_generation", sa.String(length=48), nullable=False),
        sa.Column("energy_at_generation", sa.Float(), nullable=False),
        sa.Column("session_at_generation", sa.String(length=48), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model_identifier", sa.String(length=128), nullable=False),
        sa.Column("blueprint_signature", sa.String(length=64), nullable=False),
        sa.Column("novelty_score", sa.Float(), nullable=True),
        sa.Column("play_count", sa.Integer(), nullable=False),
        sa.Column("last_played_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=True),
        sa.Column("created_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("updated_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("rejection_reason", sa.String(length=400), nullable=True),
        sa.PrimaryKeyConstraint("track_id", name=op.f("pk_tracks")),
    )
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tracks_blueprint_signature"), ["blueprint_signature"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tracks_bpm"), ["bpm"], unique=False)
        batch_op.create_index(batch_op.f("ix_tracks_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tracks_genre"), ["genre"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tracks_is_instrumental"), ["is_instrumental"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracks_last_played_at"), ["last_played_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tracks_musical_key"), ["musical_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_tracks_persona_id"), ["persona_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tracks_primary_topic"), ["primary_topic"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracks_regime_at_generation"), ["regime_at_generation"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tracks_state"), ["state"], unique=False)
        batch_op.create_index("ix_tracks_state_created", ["state", "created_at"], unique=False)
        batch_op.create_index(
            "ix_tracks_state_last_played", ["state", "last_played_at"], unique=False
        )

    op.create_table(
        "used_seeds",
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=True),
        sa.Column("used_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("seed", "provider", name=op.f("pk_used_seeds")),
    )
    with op.batch_alter_table("used_seeds", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_used_seeds_track_id"), ["track_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_used_seeds_used_at"), ["used_at"], unique=False)

    op.create_table(
        "audio_fingerprints",
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("chroma_mean", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("chroma_std", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("mfcc_mean", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("mfcc_std", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("spectral", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("embedding", tradefix_radio.persistence.types.PortableJson(), nullable=True),
        sa.Column("tempo", sa.Float(), nullable=False),
        sa.Column("musical_key", sa.String(length=32), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("blueprint_signature", sa.String(length=64), nullable=False),
        sa.Column("lyric_hash", sa.String(length=64), nullable=True),
        sa.Column("computed_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.track_id"],
            name=op.f("fk_audio_fingerprints_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("track_id", name=op.f("pk_audio_fingerprints")),
    )
    with op.batch_alter_table("audio_fingerprints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audio_fingerprints_blueprint_signature"),
            ["blueprint_signature"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_audio_fingerprints_computed_at"), ["computed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audio_fingerprints_file_sha256"), ["file_sha256"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audio_fingerprints_lyric_hash"), ["lyric_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audio_fingerprints_musical_key"), ["musical_key"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audio_fingerprints_tempo"), ["tempo"], unique=False)

    op.create_table(
        "lyrics",
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("primary_topic", sa.String(length=96), nullable=False),
        sa.Column("secondary_topic", sa.String(length=96), nullable=True),
        sa.Column("lyric_format", sa.String(length=64), nullable=False),
        sa.Column("perspective", sa.String(length=48), nullable=False),
        sa.Column("tradefix_mentions", sa.Integer(), nullable=False),
        sa.Column("educational_intensity", sa.Float(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("shingles", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("concepts_used", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("created_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.track_id"],
            name=op.f("fk_lyrics_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("track_id", name=op.f("pk_lyrics")),
    )
    with op.batch_alter_table("lyrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lyrics_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_lyrics_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_lyrics_primary_topic"), ["primary_topic"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lyrics_secondary_topic"), ["secondary_topic"], unique=False
        )
        batch_op.create_index(
            "ix_lyrics_topic_pair", ["primary_topic", "secondary_topic"], unique=False
        )

    op.create_table(
        "track_blueprints",
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("payload", tradefix_radio.persistence.types.PortableJson(), nullable=False),
        sa.Column("created_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.track_id"],
            name=op.f("fk_track_blueprints_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("track_id", name=op.f("pk_track_blueprints")),
    )
    op.create_table(
        "track_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("file_format", sa.String(length=16), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=False),
        sa.Column("deleted_at", tradefix_radio.persistence.types.UtcDateTime(), nullable=True),
        sa.Column("retain_forever", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.track_id"],
            name=op.f("fk_track_files_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_track_files")),
        sa.UniqueConstraint("track_id", "role", name="uq_track_files_track_id_role"),
    )
    with op.batch_alter_table("track_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_track_files_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_track_files_retain_forever"), ["retain_forever"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_track_files_role"), ["role"], unique=False)
        batch_op.create_index(
            "ix_track_files_role_deleted_created",
            ["role", "deleted_at", "created_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_track_files_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_track_files_track_id"), ["track_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_track_files_track_id"))
        batch_op.drop_index(batch_op.f("ix_track_files_sha256"))
        batch_op.drop_index("ix_track_files_role_deleted_created")
        batch_op.drop_index(batch_op.f("ix_track_files_role"))
        batch_op.drop_index(batch_op.f("ix_track_files_retain_forever"))
        batch_op.drop_index(batch_op.f("ix_track_files_created_at"))

    op.drop_table("track_files")
    op.drop_table("track_blueprints")
    with op.batch_alter_table("lyrics", schema=None) as batch_op:
        batch_op.drop_index("ix_lyrics_topic_pair")
        batch_op.drop_index(batch_op.f("ix_lyrics_secondary_topic"))
        batch_op.drop_index(batch_op.f("ix_lyrics_primary_topic"))
        batch_op.drop_index(batch_op.f("ix_lyrics_created_at"))
        batch_op.drop_index(batch_op.f("ix_lyrics_content_hash"))

    op.drop_table("lyrics")
    with op.batch_alter_table("audio_fingerprints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audio_fingerprints_tempo"))
        batch_op.drop_index(batch_op.f("ix_audio_fingerprints_musical_key"))
        batch_op.drop_index(batch_op.f("ix_audio_fingerprints_lyric_hash"))
        batch_op.drop_index(batch_op.f("ix_audio_fingerprints_file_sha256"))
        batch_op.drop_index(batch_op.f("ix_audio_fingerprints_computed_at"))
        batch_op.drop_index(batch_op.f("ix_audio_fingerprints_blueprint_signature"))

    op.drop_table("audio_fingerprints")
    with op.batch_alter_table("used_seeds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_used_seeds_used_at"))
        batch_op.drop_index(batch_op.f("ix_used_seeds_track_id"))

    op.drop_table("used_seeds")
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_index("ix_tracks_state_last_played")
        batch_op.drop_index("ix_tracks_state_created")
        batch_op.drop_index(batch_op.f("ix_tracks_state"))
        batch_op.drop_index(batch_op.f("ix_tracks_regime_at_generation"))
        batch_op.drop_index(batch_op.f("ix_tracks_primary_topic"))
        batch_op.drop_index(batch_op.f("ix_tracks_persona_id"))
        batch_op.drop_index(batch_op.f("ix_tracks_musical_key"))
        batch_op.drop_index(batch_op.f("ix_tracks_last_played_at"))
        batch_op.drop_index(batch_op.f("ix_tracks_is_instrumental"))
        batch_op.drop_index(batch_op.f("ix_tracks_genre"))
        batch_op.drop_index(batch_op.f("ix_tracks_created_at"))
        batch_op.drop_index(batch_op.f("ix_tracks_bpm"))
        batch_op.drop_index(batch_op.f("ix_tracks_blueprint_signature"))

    op.drop_table("tracks")
    with op.batch_alter_table("track_titles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_track_titles_track_id"))
        batch_op.drop_index(batch_op.f("ix_track_titles_title"))
        batch_op.drop_index(batch_op.f("ix_track_titles_normalised"))
        batch_op.drop_index(batch_op.f("ix_track_titles_created_at"))

    op.drop_table("track_titles")
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topics_last_used_at"))
        batch_op.drop_index(batch_op.f("ix_topics_enabled"))
        batch_op.drop_index(batch_op.f("ix_topics_certainty"))
        batch_op.drop_index(batch_op.f("ix_topics_category"))

    op.drop_table("topics")
    with op.batch_alter_table("system_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_events_track_id"))
        batch_op.drop_index(batch_op.f("ix_system_events_service"))
        batch_op.drop_index("ix_system_events_level_at")
        batch_op.drop_index(batch_op.f("ix_system_events_level"))
        batch_op.drop_index(batch_op.f("ix_system_events_job_id"))
        batch_op.drop_index(batch_op.f("ix_system_events_event"))
        batch_op.drop_index(batch_op.f("ix_system_events_at"))

    op.drop_table("system_events")
    with op.batch_alter_table("station_ids", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_station_ids_last_played_at"))
        batch_op.drop_index(batch_op.f("ix_station_ids_enabled"))
        batch_op.drop_index(batch_op.f("ix_station_ids_context"))

    op.drop_table("station_ids")
    with op.batch_alter_table("state_transitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_state_transitions_track_id"))
        batch_op.drop_index("ix_state_transitions_track_at")
        batch_op.drop_index(batch_op.f("ix_state_transitions_to_state"))
        batch_op.drop_index(batch_op.f("ix_state_transitions_reason"))
        batch_op.drop_index(batch_op.f("ix_state_transitions_at"))

    op.drop_table("state_transitions")
    with op.batch_alter_table("similarity_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_similarity_results_verdict"))
        batch_op.drop_index(batch_op.f("ix_similarity_results_track_id"))
        batch_op.drop_index(batch_op.f("ix_similarity_results_evaluated_at"))

    op.drop_table("similarity_results")
    op.drop_table("setting_overrides")
    op.drop_table("radio_memory")
    with op.batch_alter_table("queue_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_queue_items_track_id"))
        batch_op.drop_index(batch_op.f("ix_queue_items_tier"))
        batch_op.drop_index("ix_queue_items_state_position")
        batch_op.drop_index(batch_op.f("ix_queue_items_state"))
        batch_op.drop_index(batch_op.f("ix_queue_items_position"))
        batch_op.drop_index(batch_op.f("ix_queue_items_lock_level"))
        batch_op.drop_index(batch_op.f("ix_queue_items_enqueued_at"))

    op.drop_table("queue_items")
    with op.batch_alter_table("play_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_play_events_track_id"))
        batch_op.drop_index(batch_op.f("ix_play_events_tier"))
        batch_op.drop_index(batch_op.f("ix_play_events_started_at"))
        batch_op.drop_index(batch_op.f("ix_play_events_completed"))

    op.drop_table("play_events")
    with op.batch_alter_table("metric_samples", schema=None) as batch_op:
        batch_op.drop_index("ix_metric_samples_name_at")
        batch_op.drop_index(batch_op.f("ix_metric_samples_name"))
        batch_op.drop_index(batch_op.f("ix_metric_samples_at"))

    op.drop_table("metric_samples")
    with op.batch_alter_table("market_states", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_states_timestamp"))
        batch_op.drop_index("ix_market_states_symbol_timestamp")
        batch_op.drop_index(batch_op.f("ix_market_states_symbol"))
        batch_op.drop_index(batch_op.f("ix_market_states_session"))
        batch_op.drop_index(batch_op.f("ix_market_states_regime"))
        batch_op.drop_index(batch_op.f("ix_market_states_feed_status"))

    op.drop_table("market_states")
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_snapshots_timestamp"))
        batch_op.drop_index(batch_op.f("ix_market_snapshots_synthetic"))
        batch_op.drop_index("ix_market_snapshots_symbol_timestamp")
        batch_op.drop_index(batch_op.f("ix_market_snapshots_symbol"))

    op.drop_table("market_snapshots")
    with op.batch_alter_table("health_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_health_events_status"))
        batch_op.drop_index(batch_op.f("ix_health_events_component"))
        batch_op.drop_index(batch_op.f("ix_health_events_at"))

    op.drop_table("health_events")
    with op.batch_alter_table("generation_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generation_jobs_track_id"))
        batch_op.drop_index(batch_op.f("ix_generation_jobs_state"))
        batch_op.drop_index(batch_op.f("ix_generation_jobs_provider"))
        batch_op.drop_index(batch_op.f("ix_generation_jobs_priority"))
        batch_op.drop_index(batch_op.f("ix_generation_jobs_lease_owner"))
        batch_op.drop_index(batch_op.f("ix_generation_jobs_lease_expires_at"))
        batch_op.drop_index("ix_generation_jobs_lease")
        batch_op.drop_index(batch_op.f("ix_generation_jobs_error_kind"))
        batch_op.drop_index(batch_op.f("ix_generation_jobs_created_at"))
        batch_op.drop_index("ix_generation_jobs_claim")

    op.drop_table("generation_jobs")
    # ### end Alembic commands ###
