"""LyricsDirector and LyricComposer (§13, §14, §15, §16, milestones 3.6–3.7).

ADR-10: the words are composed from the station's own topic graph, not generated by a
language model. That decision is what makes §14 testable at all — every factual statement
in a lyric is a string an author wrote and marked with a certainty level — and this module
is where the claim gets checked.

The headline test is at the bottom: compose several hundred lyrics across every format,
persona and topic, and run the §17 validator over all of them. A composer that produces
text the station's own validator rejects is not a working composer, and the acceptance rate
is reported rather than assumed.
"""

from __future__ import annotations

import random
from collections import Counter
from datetime import datetime

import pytest

from tradefix_radio.config.schema import AppSettings
from tradefix_radio.contracts.enums import (
    MarketRegime,
    TradingSession,
    VocalStyle,
)
from tradefix_radio.core.clock import UTC
from tradefix_radio.director.diversity import DiversityDirector
from tradefix_radio.director.history import HistoryEntry, ProgrammingHistory
from tradefix_radio.director.library import ContentLibrary, load_content_library
from tradefix_radio.director.selection import WeightedSelector
from tradefix_radio.lyrics.composer import LyricComposer
from tradefix_radio.lyrics.director import MAX_FORMAT_ENERGY_DISTANCE, LyricsDirector
from tradefix_radio.lyrics.validators import LyricValidator, ValidationContext

from tests.unit.test_library import CONFIG_DIR

MOMENT = datetime(2026, 10, 2, 13, 0, tzinfo=UTC)


@pytest.fixture(scope="module")
def library() -> ContentLibrary:
    return load_content_library(config_dir=CONFIG_DIR)


@pytest.fixture(scope="module")
def settings() -> AppSettings:
    return AppSettings()


def lyrics_director(
    library: ContentLibrary, settings: AppSettings, seed: int = 11
) -> LyricsDirector:
    selector = WeightedSelector(random.Random(seed))
    return LyricsDirector(
        library,
        settings.lyrics,
        DiversityDirector(settings.diversity),
        selector,
    )


def composer(library: ContentLibrary, seed: int = 11) -> LyricComposer:
    return LyricComposer(library, WeightedSelector(random.Random(seed)))


def plan_for(
    library: ContentLibrary,
    settings: AppSettings,
    *,
    seed: int = 11,
    persona_key: str | None = None,
    instrumental: bool = False,
    regime: MarketRegime = MarketRegime.NORMAL_RANGE,
    session: TradingSession = TradingSession.LONDON,
    energy: float = 55.0,
    history: ProgrammingHistory | None = None,
    temperature: float = 1.0,
):
    persona = library.persona(persona_key) if persona_key else None
    style = persona.vocal_styles[0] if persona else VocalStyle.RAP
    return lyrics_director(library, settings, seed).plan(
        history=history or ProgrammingHistory([]),
        regime=regime,
        session=session,
        energy=energy,
        persona=persona,
        vocal_style=style,
        instrumental=instrumental,
        temperature=temperature,
    )


# ---------------------------------------------------------------- §13 planning


def test_an_instrumental_track_gets_a_disabled_plan_not_none(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """The blueprint's shape must never vary, so §8's coherence checks always apply."""
    plan = plan_for(library, settings, instrumental=True)
    assert not plan.enabled
    assert plan.spec.primary_topic is None
    assert plan.spec.secondary_topic is None
    assert plan.spec.tradefix_mentions == 0
    assert plan.topic is None
    assert plan.lyric_format is None
    assert "instrumental" in plan.rationale[0]


def test_a_vocal_track_gets_a_topic_and_a_format(
    library: ContentLibrary, settings: AppSettings
) -> None:
    plan = plan_for(library, settings)
    assert plan.enabled
    assert plan.topic is not None
    assert plan.lyric_format is not None
    assert plan.spec.primary_topic == plan.topic.key
    assert plan.spec.format == plan.lyric_format.key
    assert plan.rationale


def test_the_secondary_topic_is_never_the_primary(
    library: ContentLibrary, settings: AppSettings
) -> None:
    for seed in range(60):
        plan = plan_for(library, settings, seed=seed)
        if plan.secondary is not None:
            assert plan.secondary.key != plan.topic.key  # type: ignore[union-attr]


def test_a_secondary_topic_is_common_but_not_universal(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """A song about one idea is usually better than a song about two."""
    plans = [plan_for(library, settings, seed=seed) for seed in range(120)]
    with_secondary = sum(1 for plan in plans if plan.secondary is not None)
    assert 0 < with_secondary < len(plans)


def test_the_persona_drives_the_perspective(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """§13: the narrator viewpoint is part of the persona, not an independent roll."""
    for persona_key in library.persona_keys:
        plan = plan_for(library, settings, persona_key=persona_key)
        assert plan.spec.perspective == library.persona(persona_key).perspective


def test_a_track_with_no_persona_still_has_a_perspective(
    library: ContentLibrary, settings: AppSettings
) -> None:
    plan = plan_for(library, settings, persona_key=None)
    assert plan.spec.perspective in library.perspectives


def test_the_chosen_format_suits_the_energy(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """A station anthem at energy 5 and an ambient murmur at 95 are both wrong."""
    for energy in (5.0, 30.0, 60.0, 95.0):
        for seed in range(25):
            plan = plan_for(library, settings, seed=seed, energy=energy)
            assert plan.lyric_format is not None
            band = plan.lyric_format.energy
            assert band.distance_to(energy) <= MAX_FORMAT_ENERGY_DISTANCE, (
                f"format {plan.lyric_format.key} (band {band.min}-{band.max}) at "
                f"energy {energy}"
            )


def test_topics_rotate_as_history_accumulates(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """§12: repetition checks at several horizons. A fresh roll each time is not enough."""
    director = lyrics_director(library, settings)
    entries: list[HistoryEntry] = []
    chosen: list[str] = []
    for index in range(150):
        plan = director.plan(
            history=ProgrammingHistory(entries),
            regime=MarketRegime.NORMAL_RANGE,
            session=TradingSession.LONDON,
            energy=55.0,
            persona=None,
            vocal_style=VocalStyle.RAP,
            instrumental=False,
        )
        assert plan.topic is not None
        chosen.append(plan.topic.key)
        entries.insert(
            0,
            HistoryEntry(
                track_id=f"TF-{index}",
                genre="deep_house",
                bpm=122,
                musical_key="A minor",
                duration_seconds=210.0,
                is_instrumental=False,
                vocal_style="rap",
                blueprint_signature=f"sig-{index}",
                energy_at_generation=55.0,
                regime_at_generation="normal_range",
                created_at=MOMENT,
                played_at=MOMENT,
                primary_topic=plan.topic.key,
                secondary_topic=plan.secondary.key if plan.secondary else None,
            ),
        )
    counts = Counter(chosen)
    assert len(counts) >= 15, f"only {len(counts)} topics across 150 tracks"
    assert counts.most_common(1)[0][1] / len(chosen) < 0.2
    # No topic twice in a row, which is the one repetition a listener cannot miss.
    assert all(chosen[i] != chosen[i - 1] for i in range(1, len(chosen)))


def test_the_regime_influences_what_the_station_talks_about(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """§1 reaches the lyrics too, not only the music."""
    def topics(regime: MarketRegime) -> Counter[str]:
        return Counter(
            plan_for(library, settings, seed=seed, regime=regime).topic.key  # type: ignore[union-attr]
            for seed in range(90)
        )

    quiet = topics(MarketRegime.QUIET)
    violent = topics(MarketRegime.EXTREME_VOLATILITY)
    quiet_top = {key for key, _ in quiet.most_common(4)}
    violent_top = {key for key, _ in violent.most_common(4)}
    assert quiet_top != violent_top, "the regime has no effect on subject matter"


def test_educational_intensity_is_a_fraction(
    library: ContentLibrary, settings: AppSettings
) -> None:
    for seed in range(60):
        plan = plan_for(library, settings, seed=seed)
        assert 0.0 <= plan.spec.educational_intensity <= 1.0


def test_brand_mentions_stay_within_the_configured_bound(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """§16: the station name is a signature, not a jingle."""
    limit = max(int(k) for k in settings.lyrics.tradefix_mention_weights)
    for seed in range(120):
        plan = plan_for(library, settings, seed=seed)
        assert 0 <= plan.spec.tradefix_mentions <= limit


def test_brand_mention_counts_match_the_configured_distribution(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """Milestone 3.8's exit test: the §16 distribution over 1000 draws.

    Checked on **vocal** tracks only. An instrumental track has no lyrics, so its zero is a
    structural fact rather than a draw — and mixing the two made the §3.12 report read
    77/18/5 against a configured 55/35/10 and look like a defect when it was not.

    The tolerance is generous because §95's temperature legitimately sharpens and flattens
    every weighted sample, including this one. What is being verified is that the configured
    weights are the thing being sampled, not that sampling is temperature-free.
    """
    weights = settings.lyrics.tradefix_mention_weights
    director = lyrics_director(library, settings)
    counts: Counter[int] = Counter()
    for index in range(1000):
        plan = director.plan(
            history=ProgrammingHistory([]),
            regime=MarketRegime.NORMAL_RANGE,
            session=TradingSession.LONDON,
            energy=(20.0, 50.0, 80.0)[index % 3],
            persona=None,
            vocal_style=VocalStyle.RAP,
            instrumental=False,
        )
        counts[plan.spec.tradefix_mentions] += 1

    assert set(counts) <= set(weights), f"unconfigured mention counts: {set(counts) - set(weights)}"
    for value, weight in sorted(weights.items()):
        observed = counts[value] / 1000
        assert abs(observed - weight) < 0.15, (
            f"{value} mention(s): configured {weight:.0%}, observed {observed:.1%}"
        )
    # The ordering must hold exactly even where the magnitudes drift.
    by_weight = [value for value, _ in sorted(weights.items(), key=lambda kv: -kv[1])]
    by_observed = [value for value, _ in counts.most_common()]
    assert by_observed == by_weight, f"ordering {by_observed} does not match {by_weight}"


# ---------------------------------------------------------------- composition


def test_an_instrumental_plan_composes_nothing(
    library: ContentLibrary, settings: AppSettings
) -> None:
    plan = plan_for(library, settings, instrumental=True)
    assert composer(library).compose(track_id="TF-1", plan=plan) is None


def test_a_composed_lyric_has_text_sections_and_tagged_lines(
    library: ContentLibrary, settings: AppSettings
) -> None:
    plan = plan_for(library, settings)
    composed = composer(library).compose(track_id="TF-1", plan=plan)
    assert composed is not None
    assert composed.lyrics.text.strip()
    assert composed.sections
    assert composed.lyrics.lines
    assert all(line.text.strip() for line in composed.lyrics.lines)
    assert {line.section for line in composed.lyrics.lines} <= set(composed.sections)


def test_the_lyric_agrees_with_its_own_plan(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """A lyric that contradicts the blueprint it came from breaks §46 and §19 both."""
    for seed in range(40):
        plan = plan_for(library, settings, seed=seed)
        composed = composer(library, seed).compose(track_id="TF-1", plan=plan)
        assert composed is not None
        assert composed.lyrics.primary_topic == plan.spec.primary_topic
        assert composed.lyrics.secondary_topic == plan.spec.secondary_topic
        assert composed.lyrics.format == plan.spec.format
        assert composed.lyrics.perspective == plan.spec.perspective
        assert composed.lyrics.tradefix_mentions == plan.spec.tradefix_mentions


def test_the_section_order_follows_the_format(
    library: ContentLibrary, settings: AppSettings
) -> None:
    for seed in range(40):
        plan = plan_for(library, settings, seed=seed)
        composed = composer(library, seed).compose(track_id="TF-1", plan=plan)
        assert composed is not None
        assert plan.lyric_format is not None
        declared = list(plan.lyric_format.sections)
        # The composer may append a trailing outro to place unused brand mentions.
        assert composed.sections[: len(declared)] == tuple(declared)


def test_the_hook_is_one_hook_repeated(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """Three different choruses is three verses. A hook is a hook because it returns."""
    for seed in range(60):
        plan = plan_for(library, settings, seed=seed)
        if plan.lyric_format is None:
            continue
        hook_sections = [s for s in plan.lyric_format.sections if "hook" in s or "chorus" in s]
        if len(hook_sections) < 2:
            continue
        composed = composer(library, seed).compose(track_id="TF-1", plan=plan)
        assert composed is not None
        by_section: dict[str, list[str]] = {}
        for line in composed.lyrics.lines:
            by_section.setdefault(line.section, []).append(line.text)
        bodies = [
            tuple(by_section[name]) for name in hook_sections if name in by_section
        ]
        # Brand injection may alter one occurrence, so require a shared core rather than
        # exact equality across all of them.
        if len(bodies) >= 2:
            assert len(set(bodies)) < len(bodies) or any(
                set(bodies[0]) & set(other) for other in bodies[1:]
            ), f"hook sections share no lines: {bodies}"


def test_the_brand_appears_exactly_as_often_as_promised(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """A count the blueprint promised and the lyric did not deliver is a reporting lie.

    The failure this pins: a format whose sections are all hooks had nowhere to inject
    during the section loop, and the trailing section placed only one mention when two
    were asked for.
    """
    for seed in range(120):
        plan = plan_for(library, settings, seed=seed)
        composed = composer(library, seed).compose(track_id="TF-1", plan=plan)
        assert composed is not None
        expected = plan.spec.tradefix_mentions
        actual = composed.lyrics.text.lower().count("trade fix")
        assert actual >= expected, (
            f"promised {expected} mentions, delivered {actual}"
        )


def test_teaching_points_are_recorded_when_used(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """§12's concept history has to be accurate or the anti-repetition is fiction."""
    used_any = False
    for seed in range(60):
        plan = plan_for(library, settings, seed=seed)
        composed = composer(library, seed).compose(track_id="TF-1", plan=plan)
        assert composed is not None
        for concept in composed.concepts:
            used_any = True
            assert concept in composed.lyrics.text
        assert composed.lyrics.concepts_used == composed.concepts
    assert used_any, "no teaching point used in 60 lyrics"


def test_composition_is_deterministic_for_a_seed(
    library: ContentLibrary, settings: AppSettings
) -> None:
    plan = plan_for(library, settings)
    first = composer(library, 77).compose(track_id="TF-1", plan=plan)
    second = composer(library, 77).compose(track_id="TF-1", plan=plan)
    assert first is not None and second is not None
    assert first.lyrics.text == second.lyrics.text


def test_different_seeds_compose_different_text(
    library: ContentLibrary, settings: AppSettings
) -> None:
    plan = plan_for(library, settings)
    texts = {
        composer(library, seed).compose(track_id="TF-1", plan=plan).lyrics.text  # type: ignore[union-attr]
        for seed in range(15)
    }
    assert len(texts) > 10, "composition barely varies with the seed"


def test_no_lyric_repeats_a_line_verbatim(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """Outside the hook, a repeated line is a generator looping.

    This is what caught the first deduplication design: deduplicating by line hid a
    looping generator, because the loop's output collapsed to a single line and looked
    clean.
    """
    # Hook and outro sections are excluded via the composer's own role map rather than by
    # guessing at section names. Guessing missed "phrase" — a hook under another name — and
    # reported a hook's deliberate closing refrain as a looping generator. A hook repeats
    # internally by design; that is what makes it a hook.
    from tradefix_radio.lyrics.composer import _ROLE_BY_SECTION

    for seed in range(80):
        plan = plan_for(library, settings, seed=seed)
        composed = composer(library, seed).compose(track_id="TF-1", plan=plan)
        assert composed is not None
        body = [
            line.text
            for line in composed.lyrics.lines
            if _ROLE_BY_SECTION.get(line.section, "body") not in {"hook", "close"}
        ]
        assert len(set(body)) == len(body), f"repeated body line: {body}"


# ---------------------------------------------------------------- §14 / §17


def test_an_uncertain_topic_is_hedged(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """§14: "must never pretend a simplified relationship guarantees price direction"."""
    from tradefix_radio.lyrics.validators import HEDGE_WORDS

    checked = 0
    for key, topic in library.topics.items():
        if not topic.requires_hedging:
            continue
        plan = plan_for(library, settings, seed=hash(key) % 1000)
        # Force the uncertain topic rather than waiting for it to be selected.
        plan = type(plan)(
            spec=plan.spec.model_copy(update={"primary_topic": key}),
            topic=topic,
            secondary=None,
            lyric_format=plan.lyric_format,
            rationale=plan.rationale,
        )
        composed = composer(library, 5).compose(track_id="TF-1", plan=plan)
        assert composed is not None
        text = composed.lyrics.text.lower()
        assert any(word in text for word in HEDGE_WORDS), (
            f"{key} ({topic.certainty}) composed with no hedge:\n{composed.lyrics.text}"
        )
        checked += 1
    assert checked > 5, f"only {checked} hedged topics exercised"


def test_no_lyric_uses_its_topics_own_forbidden_phrases(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """Per-topic overclaims: the thing §14 says that topic specifically must not assert."""
    for seed in range(150):
        plan = plan_for(library, settings, seed=seed)
        composed = composer(library, seed).compose(track_id="TF-1", plan=plan)
        assert composed is not None
        text = composed.lyrics.text.lower()
        for topic in (plan.topic, plan.secondary):
            if topic is None:
                continue
            for phrase in topic.forbidden:
                assert phrase.lower() not in text, (
                    f"{topic.key} forbids {phrase!r}:\n{composed.lyrics.text}"
                )


def test_every_composed_lyric_passes_the_stations_own_validator(
    library: ContentLibrary, settings: AppSettings
) -> None:
    """The headline test, and the reason the composer went through six revisions.

    A composer whose output the station's own §17 validator rejects is not a working
    composer: every rejection costs a generation cycle, and a persistent rejection rate
    means the station eventually runs out of attempts and airs the fallback.

    Started at 75.2% acceptance. The rate is asserted at 100% rather than at a tolerance,
    because the composer draws from a closed, authored corpus — there is no reason for any
    output to be invalid, so any failure here is a real defect rather than noise.
    """
    validator = LyricValidator(settings.lyrics)
    director = lyrics_director(library, settings)
    comp = composer(library)
    entries: list[HistoryEntry] = []
    failures: list[tuple[str, str]] = []
    word_counts: list[int] = []
    composed_count = 0

    personas = list(library.persona_keys)
    for index in range(300):
        persona_key = personas[index % len(personas)]
        persona = library.persona(persona_key)
        energy = (10.0, 35.0, 55.0, 75.0, 95.0)[index % 5]
        plan = director.plan(
            history=ProgrammingHistory(entries),
            regime=list(MarketRegime)[index % len(MarketRegime)],
            session=list(TradingSession)[index % len(TradingSession)],
            energy=energy,
            persona=persona,
            vocal_style=persona.vocal_styles[0],
            instrumental=False,
            temperature=(0.4, 1.0, 1.4)[index % 3],
        )
        composed = comp.compose(track_id=f"TF-{index:05d}", plan=plan, persona=persona)
        assert composed is not None
        composed_count += 1
        word_counts.append(len(composed.lyrics.normalised_text.split()))

        result = validator.validate(
            composed.lyrics,
            ValidationContext(
                primary_topic=plan.topic,
                secondary_topic=plan.secondary,
                expected_mentions=plan.spec.tradefix_mentions,
                format_min_words=plan.lyric_format.min_words if plan.lyric_format else None,
                format_max_words=plan.lyric_format.max_words if plan.lyric_format else None,
            ),
        )
        if not result.accepted:
            failures.append(
                (
                    f"{plan.lyric_format.key if plan.lyric_format else '?'}/{persona_key}",
                    "; ".join(v.detail for v in result.violations),
                )
            )
        assert plan.topic is not None
        entries.insert(
            0,
            HistoryEntry(
                track_id=f"TF-{index:05d}",
                genre=persona.genres[0],
                bpm=120,
                musical_key="A minor",
                duration_seconds=210.0,
                is_instrumental=False,
                vocal_style=persona.vocal_styles[0].value,
                blueprint_signature=f"sig-{index}",
                energy_at_generation=energy,
                regime_at_generation="normal_range",
                created_at=MOMENT,
                played_at=MOMENT,
                primary_topic=plan.topic.key,
                secondary_topic=plan.secondary.key if plan.secondary else None,
                persona_id=persona_key,
            ),
        )

    assert composed_count == 300
    assert not failures, (
        f"{len(failures)}/300 composed lyrics failed the §17 validator; first five:\n"
        + "\n".join(f"  {where}: {why}" for where, why in failures[:5])
    )
    # Word counts span the formats' declared range rather than clustering at one length.
    assert min(word_counts) < 60 < max(word_counts), (
        f"word counts {min(word_counts)}-{max(word_counts)} — the formats are not varying"
    )
